# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User: plaintext

    providers:
        database_users:
            entity:
                class: AppBundle:User
                property: email

    firewalls:
        secured_area:

            pattern: ^/

            anonymous: true

            form_login:
                username_parameter: _email

                login_path: login

                check_path: login

                csrf_token_generator: security.csrf.token_manager

                default_target_path: index_admin

            logout:
                path: logout

                target: homepage

    access_control:
        - { path: /admin, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: /article/new, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: /category/new, roles: IS_AUTHENTICATED_REMEMBERED }
